### 1️⃣ Retrieve all todos
GET http://localhost:5017/todos


### 2️⃣ Create a new todo
POST http://localhost:5017/todos
Content-Type: application/json

{
  "name": "Complete .NET API",
  "dueDate": "2030-04-01",
  "isCompleted": false
}


### 3️⃣ Retrieve a todo by ID (Replace `1` with actual ID)
GET http://localhost:5017/todos/2


### 4️⃣ Update a todo (Replace `1` with actual ID)
PUT http://localhost:5017/todos/1
Content-Type: application/json

{
  "name": "Update .NET API",
  "dueDate": "2025-04-05T15:00:00Z",
  "isCompleted": true
}


### 5️⃣ Delete a todo (Replace `1` with actual ID)
DELETE http://localhost:5017/todos/5

### 3️⃣ Retrieve a todo by tasks redirection ID
GET http://localhost:5017/tasks/2
