name: Generate Changelog

on:
  release:
    types: [published]  # Trigger on new release

jobs:
  generate-changelog:
    runs-on: ubuntu-latest  # This is the OS that the action runs on
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Generate Changelog
        run: |
          gem install github_changelog_generator
          github_changelog_generator --user arpan-maruti --project Training
        env:
          GITHUB_TOKEN: ${{ secrets.Arpan }}
      
      - name: Commit and push changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push
